name: Build macOS and Windows Apps

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build macOS app
        run: |
          pyinstaller --noconfirm --windowed --icon=icon.icns test.py

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Create dmg file
        run: |
          create-dmg \
            --volname "Test App" \
            --window-pos 200 120 \
            --window-size 500 300 \
            --icon-size 100 \
            --icon "test.app" 125 125 \
            --hide-extension "test.app" \
            --app-drop-link 375 125 \
            dist/test.app \
            dist/TestApp.dmg

      - name: Upload macOS dmg artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-dmg
          path: dist/TestApp.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows exe
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico test.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/test.exe
